dataset: /home/zhampel/insight/data/cifar-10-images/
models_to_run: model1
#, model2

model1:
    #outpath: saved_models
    layers: conv2d, conv2d, conv2d
    batch_size: 1
    epochs: 10
    validation_split: 0.2

model2:
    #outpath: saved_models/poop
    layers: conv2d_4rot, conv2d_4rot, conv2d_4rot
    batch_size: 128
    validation_split: 0.2

